### ISSUE TITLE
To-do (v0.0.0)

### ISSUE THREAD

**Issue by tay10r** [tay10r/rtl#3]
This issue tracks everything that needs to be done for a complete working demo of the project (and the first release.) This list will probably continue to grow, change, and is not exhaustive.

Major items:

 - [ ] Texture Atlas Construction and UV Mapping
 - [ ] Better Tile Generation
 - [ ] Best Swizzle Pattern Determination
 - [ ] Vertical Swizzling Pattern
 - [ ] Morton Swizzling Pattern
 - [ ] Shader Packet Design
 - [ ] Unswizzling GLSL Shader
 - [ ] FXAA GLSL Shader

Below are more details of the major to-do items.

### Texture Atlas Construction and UV Mapping

In a single tile, there may be a large number of textures referenced. OpenGL can only (portably) use a single texture at a time. In order to circumvent this limitation, a texture atlas needs to be built so that OpenGL can bind it and use it for all of the tile renderings. This has the additional benefit that texture indices don't need to be stored by any of the geometry.

This requires the following classes:

```cxx
template <typename color_type>
class texture_atlas_builder final
{
public:
  using texture_id = size_type;
  texture_id load_image(const char* path);
  texture_id add_color(color_type r, color_type g, color_type b, color_type a);
  texture_atlas build() const;
};
```

```cxx
template <typename color_type>
class texture_atlas final
{
public:
  /* TODO : using real_type = ... */
  using rgba = vector<color_type, 4, 1>;
  using texture_id = size_type;
  using vec2_type = vector<real_type, 2, 1>;

  /* For assigning UV coordinates to geometry */
  vec2_type map_coordinates(texture_id texture, const vec2_type& in) const noexcept;
  const color_type* data() const noexcept;
  size_type width() const noexcept;
  size_type height() const noexcept;
};
```

### Better Tile Generation

There's currently a limitation to the tile area generation that makes the areas only work best for Morton swizzle patterns. This is because only square tiles are generated. This becomes an issue for areas of the image that don't perfectly fit into 4x4 squares. What ends up happening is a lot of really small 1x1 tiles get generated. Ideally, this can be handled as a special case so that larger vertical are horizontal area strips are generated instead.

### Best Swizzle Pattern Determination

Programs should be able to determine the best swizzling pattern based on the dimensions of the tile area. Square tiles will probably work best with the Morton ordered swizzling pattern (this needs testing to verify.) Long vertical strips will work best with vertically ordered rays. Long horizontal strips will work best with horizontally ordered rays (scanline ordered rays.)

### Vertical Swizzling Pattern

A swizzling pattern to handle long vertical tile areas.

### Morton Swizzing Pattern

This is already implemented in the documentation but requires implementation in the main library and automated testing.

### Shader Packet Design

A shader packet will determine what data is needed for the GLSL shaders to probably render the path that was traced by the rays. These will only be able to carry a limited amount of information, due to the bandwidth limitations of CPU-to-GPU transfers. It will also affect the practical limitation of the maximum ray recursion depth. The more a ray is recursively traced, the larger the path becomes, and the more data that will be required to be transferred. Here's a draft of what a shader packet might look like.

```cxx
template <size_type scalar_size, size_type packet_size>
struct shader_packet final
{
  using real_type = typename associated_types<scalar_size>::real_type;
  // maps to texture atlas
  vector<real_type, 2, packet_size> uv;
  // how much each sample is occluded.
  vector<real_type, 1, packet_size> occlusion;
};
```

### Unswizzling GLSL Shader

The data sent to the shaders may be out of order due to SIMD layouts and other swizzling patterns. A GLSL shader can be used to reorder the data before sending it to the other shaders for processing.

### FXAA GLSL Shader

Traditional MSAA sampling for ray tracing is not practical for this project because:

 - MSAA requires a lot more rays to be traced, which is too slow on the CPU
 - MSAA requires a lot more data to be transfered to the GPU

FXAA is more ideal because it can be done on the GPU and doesn't require more rays to be traced.
